import { StyleSheet, Platform, Dimensions } from 'react-native';
import { COLORS } from '../../constants';
import { hp, wp } from '../../utils/responsive';

const { width } = Dimensions.get('window');

const styles = StyleSheet.create({
  container: {
    flex: 1,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 20,
    paddingTop: 10,
    paddingBottom: 20,
  },
  iconContainer: {
    width: 40,
    height: 40,
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 10,
  },
  icon: {
    width: 24,
    height: 24,
  },
  heading: {
    fontSize: 20,
    fontWeight: '700',
    color: COLORS.white,
    textAlign: 'center',
    fontFamily: 'Outfit-Bold',
    flex: 1,
  },
  mainContainer: {
    flex: 1,
    backgroundColor: '#FEF9F5',
    borderTopLeftRadius: 30,
    borderTopRightRadius: 30,
    paddingHorizontal: 20,
    paddingTop: 25,
  },
  introContainer: {
    backgroundColor: 'rgba(255, 165, 0, 0.1)',
    padding: 15,
    borderRadius: 15,
    marginBottom: 20,
    borderWidth: 1,
    borderColor: 'rgba(255, 165, 0, 0.2)',
  },
  subHeading: {
    fontSize: hp(18),
    fontWeight: '600',
    color: COLORS.black,
    marginBottom: 10,
    lineHeight: hp(24),
    fontFamily: 'Outfit-SemiBold',
    textAlign: 'center',
  },
  description: {
    fontSize: hp(15),
    color: COLORS.black,
    lineHeight: hp(22),
    fontFamily: 'Outfit-Regular',
    textAlign: 'center',
  },
  inputContainer: {
    marginBottom: 10,
  },
  label: {
    fontSize: hp(14),
    fontWeight: '600',
    color: COLORS.black,
    marginBottom: 4,
    fontFamily: 'Outfit-SemiBold',
  },
  input: {
    borderWidth: 1,
    borderColor: 'rgba(0,0,0,0.05)',
    borderRadius: 15,
    paddingVertical: 15,
    paddingHorizontal: 15,
    fontSize: hp(14),
    color: COLORS.black,
    backgroundColor: COLORS.white,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.1,
    shadowRadius: 8,
    elevation: 4,
    marginHorizontal: 8,
    marginBottom: 4,
    fontFamily: 'Outfit-Regular',
  },
  textarea: {
    borderWidth: 1,
    borderColor: 'rgba(0,0,0,0.05)',
    borderRadius: 15,
    paddingTop: 15,
    paddingHorizontal: 15,
    fontSize: hp(14),
    color: COLORS.black,
    backgroundColor: COLORS.white,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.1,
    shadowRadius: 8,
    elevation: 4,
    height: 100,
    textAlignVertical: 'top',
    marginHorizontal: 8,
    marginBottom: 4,
    fontFamily: 'Outfit-Regular',
  },
  rulesList: {
    flex: 1,
    marginBottom: 20,
  },
  ruleItem: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: COLORS.white,
    paddingVertical: 15,
    paddingHorizontal: 20,
    borderRadius: 15,
    marginBottom: 12,
    marginHorizontal: 8,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.1,
    shadowRadius: 8,
    elevation: 4,
    borderWidth: 1,
    borderColor: 'rgba(0,0,0,0.05)',
  },
  checkbox: {
    width: 24,
    height: 24,
    borderRadius: 4,
    borderWidth: 2,
    borderColor: COLORS.orange,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 12,
  },
  checkboxChecked: {
    backgroundColor: COLORS.orange,
  },
  ruleText: {
    flex: 1,
    fontSize: hp(15),
    color: COLORS.black,
    lineHeight: hp(22),
    fontFamily: 'Outfit-Regular',
  },
  ruleTextChecked: {
    color: COLORS.orange,
    fontFamily: 'Outfit-Bold',
  },
  buttonContainer: {
    paddingVertical: 20,
    backgroundColor: 'transparent',
  },
  button: {
    backgroundColor: COLORS.orange,
    height: 55,
    borderRadius: 15,
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: COLORS.orange,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 5,
  },
  buttonText: {
    color: COLORS.white,
    fontSize: 18,
    fontWeight: '700',
    letterSpacing: 0.5,
    fontFamily: 'Outfit-Bold',
  },
  errorText: {
    color: '#ff4d4d',
    fontSize: hp(12),
    marginTop: 5,
    marginLeft: 5,
    fontFamily: 'Outfit-Regular',
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 20,
  },
  modalContent: {
    width: '100%',
    backgroundColor: COLORS.white,
    borderRadius: 20,
    padding: 20,
    maxHeight: '80%',
  },
  modalTitle: {
    fontSize: hp(20),
    fontWeight: '700',
    color: COLORS.black,
    marginBottom: 20,
    textAlign: 'center',
    fontFamily: 'Outfit-Bold',
  },
  statsItem: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(0,0,0,0.05)',
  },
  statsTitle: {
    fontSize: hp(15),
    color: COLORS.black,
    fontFamily: 'Outfit-Medium',
    flex: 1,
    marginRight: 10,
  },
  statsCountContainer: {
    backgroundColor: 'rgba(255, 165, 0, 0.1)',
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 12,
  },
  statsCount: {
    fontSize: hp(14),
    color: COLORS.orange,
    fontFamily: 'Outfit-Bold',
  },
  closeModalButton: {
    marginTop: 20,
    backgroundColor: COLORS.orange,
    paddingVertical: 12,
    borderRadius: 10,
    alignItems: 'center',
  },
  closeModalButtonText: {
    color: COLORS.white,
    fontSize: hp(16),
    fontFamily: 'Outfit-Bold',
  },
});

export default styles;
