import { StyleSheet, Platform } from 'react-native';
import { hp, wp } from '../../utils/responsive';
import { COLORS } from '../../constants';

const styles = StyleSheet.create({
  container: {
    flex: 1,
  },
  mainContainer: {
    backgroundColor: '#FEF9F5',
    flex: 1,
    padding: 20,
    paddingTop: 15,
    borderTopLeftRadius: 30,
    borderTopRightRadius: 30,
    overflow: 'hidden',
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 20,
    paddingTop: 10,
    paddingBottom: 20,
  },
  heading: {
    fontWeight: '700',
    fontSize: 20,
    color: COLORS.white,
    textAlign: 'center',
    fontFamily: 'Outfit-Bold',
    flex: 1,
  },
  icon: {
    height: 24,
    width: 24,
  },
  iconContainer: {
    width: 40,
    height: 40,
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 10,
  },
  inputContainer: {
    marginBottom: 10,
  },
  label: {
    fontWeight: '600',
    fontSize: hp(14),
    color: COLORS.black,
    fontFamily: 'Outfit-SemiBold',
    marginBottom: 4,
  },
  input: {
    backgroundColor: COLORS.white,
    borderRadius: 15,
    paddingVertical: 15,
    paddingHorizontal: 15,
    fontSize: hp(14),
    color: COLORS.black,
    fontFamily: 'Outfit-Regular',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.1,
    shadowRadius: 8,
    elevation: 4,
    borderWidth: 1,
    borderColor: 'rgba(0,0,0,0.05)',
    marginHorizontal: 8,
    marginBottom: 4,
  },
  messageInput: {
    backgroundColor: COLORS.white,
    borderRadius: 15,
    paddingTop: 15,
    paddingHorizontal: 15,
    fontSize: hp(14),
    color: COLORS.black,
    fontFamily: 'Outfit-Regular',
    height: 120,
    textAlignVertical: 'top',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.1,
    shadowRadius: 8,
    elevation: 4,
    borderWidth: 1,
    borderColor: 'rgba(0,0,0,0.05)',
    marginHorizontal: 8,
    marginBottom: 4,
  },
  buttonContainer: {
    flexDirection: 'column',
    marginTop: 20,
  },
  button: {
    backgroundColor: COLORS.orange,
    height: 55,
    borderRadius: 15,
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: COLORS.orange,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 5,
    flexDirection: 'row',
  },
  buttonText: {
    color: COLORS.white,
    fontSize: 18,
    fontWeight: '700',
    fontFamily: 'Outfit-Bold',
    marginLeft: 10,
  },
  errorText: {
    color: '#ff4d4d',
    fontSize: hp(12),
    marginTop: 5,
    marginLeft: 5,
    fontFamily: 'Outfit-Regular',
  },
});

export default styles;
