import { StyleSheet } from 'react-native';
import { hp, wp } from '../../utils/responsive';

export default StyleSheet.create({
  bottomBarContainer: {
    position: 'absolute',
    bottom: hp(20),
    left: wp(16),
    right: wp(16),
    height: hp(65),
    backgroundColor: '#333333',
    borderRadius: hp(35),
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: wp(12),
    elevation: 10,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 5 },
    shadowOpacity: 0.4,
    shadowRadius: 6,
  },
  bottomBarIconContainer: {
    flex: 1,
    height: '100%',
    justifyContent: 'center',
    alignItems: 'center',
  },
  bottomBarDivider: {
    width: 1,
    height: hp(20),
    backgroundColor: '#444',
  },
  expandedMenuContainer: {
    position: 'absolute',
    bottom: hp(95),
    left: 0,
    right: 0,
    alignItems: 'center',
    zIndex: 100,
  },
  fullScreenOverlay: {
    position: 'absolute',
    top: 0,
    bottom: 0,
    left: 0,
    right: 0,
    zIndex: 90,
  },
  expandedMenuOverlay: {
    backgroundColor: '#333333',
    borderRadius: hp(25),
    flexDirection: 'row',
    padding: hp(18),
    paddingHorizontal: wp(25),
    justifyContent: 'space-between',
    alignItems: 'center',
    width: '92%',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.5,
    shadowRadius: 15,
    elevation: 12,
  },
  gridMenuOverlay: {
    backgroundColor: '#333333',
    borderRadius: hp(25),
    padding: hp(20),
    paddingVertical: hp(25),
    width: '92%',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.5,
    shadowRadius: 15,
    elevation: 12,
  },
  gridRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: hp(18),
  },
  gridMenuItem: {
    alignItems: 'center',
    width: '25%',
  },
  menuItem: {
    alignItems: 'center',
  },
  menuIconWrapper: {
    marginBottom: hp(8),
  },
  menuItemText: {
    color: '#e48616',
    fontSize: hp(12),
    marginTop: hp(5),
    textAlign: 'center',
    fontFamily: 'Outfit-Medium',
  },
});
