import { StyleSheet, Platform } from 'react-native';
import { hp, wp } from '../../utils/responsive';
import { COLORS } from '../../constants';

const styles = StyleSheet.create({
  container: {
    flex: 1,
    width: '100%',
    height: '100%',
  },
  mainContainer: {
    backgroundColor: '#FEF9F5',
    flex: 1,
    paddingHorizontal: 15,
    paddingTop: 5,
    borderTopLeftRadius: 30,
    borderTopRightRadius: 30,
    overflow: 'hidden',
  },
  headerText: {
    fontSize: 20,
    fontWeight: '700',
    color: COLORS.white,
    textAlign: 'center',
    fontFamily: 'Outfit-Bold',
    flex: 1,
  },
  searchContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    marginVertical: hp(10),
    marginHorizontal: 20,
    backgroundColor: 'rgba(255, 255, 255, 0.2)',
    borderRadius: hp(10),
    paddingHorizontal: 12,
    borderColor: 'rgba(255, 255, 255, 0.4)',
    borderWidth: hp(1),
  },
  searchInput: {
    flex: 1,
    fontSize: 16,
    color: 'white',
    paddingVertical: 8,
    fontFamily: 'Outfit-Regular',
  },
  voiceButton: {
    width: hp(40),
    height: hp(40),
    borderRadius: 20,
    justifyContent: 'center',
    alignItems: 'center',
    marginLeft: 8,
  },
  sectionHeaderContainer: {
    paddingTop: hp(5),
    paddingBottom: 0,
    paddingHorizontal: 15,
  },
  sectionHeader: {
    fontSize: hp(18),
    fontWeight: '700',
    lineHeight: hp(24),
    color: COLORS.black,
    fontFamily: 'Outfit-Bold',
  },
  cardImage: {
    height: hp(180),
    borderRadius: hp(15),
  },
  recentCardText: {
    fontSize: hp(12),
    lineHeight: 16,
    fontWeight: '400',
    color: COLORS.firefly,
  },
  recentCardTimeText: {
    fontSize: hp(12),
    lineHeight: hp(16),
    fontWeight: '400',
    color: COLORS.firefly,
    marginTop: hp(10),
  },
  progressBackground: {
    height: hp(12),
    backgroundColor: COLORS.cinderella,
    borderRadius: hp(10),
    overflow: 'hidden',
    marginTop: hp(10),
  },
  progressBar: {
    height: '100%',
    backgroundColor: COLORS.flamingo,
    borderRadius: hp(10),
  },
  separator: {
    height: hp(10),
  },
  header: {
    height: hp(43),
    marginBottom: hp(10),
  },
  sectionViewAll: {
    fontSize: hp(15),
    lineHeight: hp(22),
    fontWeight: '500',
    color: COLORS.firefly,
  },
  AudioContainer: {
    backgroundColor: COLORS.white,
    shadowOpacity: 0.1,
    elevation: 4,
    borderRadius: 20,
    marginBottom: hp(10),
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.1,
    shadowRadius: 10,
    overflow: 'hidden',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.3)',
    minHeight: hp(280),
    width: '100%',
  },
  audioCardImage: {
    height: hp(180),
    width: '100%',
  },
  audioTextContainer: {
    padding: hp(15),
  },
  audioCardTitle: {
    fontSize: hp(16),
    lineHeight: hp(22),
    fontWeight: '700',
    color: COLORS.firefly,
    fontFamily: 'Outfit-Bold',
  },
  audioCardDescription: {
    fontSize: hp(13),
    lineHeight: hp(18),
    fontWeight: '400',
    color: '#666',
    marginTop: hp(5),
    fontFamily: 'Outfit-Regular',
  },
  iconContainer: {
    position: 'absolute',
    borderRadius: 25,
    height: 50,
    width: 50,
    backgroundColor: COLORS.white,
    shadowOpacity: 0.1,
    elevation: 4,
    justifyContent: 'center',
    alignItems: 'center',
    top: hp(65),
    left: '50%',
    marginLeft: -25,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 4,
    elevation: 5,
  },
  imageContainer: {
    marginTop: wp(10),
    flexDirection: 'row',
  },
  oneXText: {
    fontSize: hp(15),
    lineHeight: hp(22),
    fontWeight: '700',
    color: COLORS.firefly,
    textAlign: 'center',
  },
  chakraStyle: {
    position: 'absolute',
    right: hp(-200),
    top: hp(-200),
    height: hp(450),
    width: hp(470),
    opacity: 0.4,
  },
  headerSubContainer: {
    justifyContent: 'center',
    alignItems: 'center',
    width: 44,
    height: 44,
    position: 'absolute',
    left: 20,
    top: 20,
    bottom: 0,
    zIndex: 10,
  },
  icon: {
    height: hp(24),
    width: hp(24),
  },
  iconPlay: {
    height: hp(20),
    width: wp(20),
    color: '#ffffff',
  },
  headerContainer: {
    paddingHorizontal: 20,
    paddingTop: 10,
    paddingBottom: 0,
    height: hp(75),
    justifyContent: 'center',
    alignItems: 'center',
    flexDirection: 'row',
  },
  headerSearchContainer: {
    justifyContent: 'center',
    alignItems: 'center',
    width: 44,
    height: 44,
  },
  rightIconContainer: {
    position: 'absolute',
    right: 20,
    top: 10,
    bottom: 0,
    justifyContent: 'center',
    zIndex: 10,
  },
  headerBellContainer: {
    justifyContent: 'center',
    alignItems: 'center',
    marginLeft: wp(20),
  },
  recentViewContainer: {
    backgroundColor: COLORS.white,
    borderRadius: 20,
    marginBottom: hp(10),
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.1,
    shadowRadius: 10,
    elevation: 4,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.3)',
    minHeight: hp(280),
    overflow: 'hidden',
    width: '100%',
  },
  recentTextContainer: {
    width: '100%',
    padding: hp(15),
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'transparent',
  },
  audioCardText: {
    fontSize: hp(16),
    lineHeight: hp(22),
    fontWeight: '400',
    color: COLORS.black,
    textAlign: 'center',
    fontFamily: 'Outfit-Medium',
  },
  cardSeparator: {
    height: 1,
    backgroundColor: '#f0f0f0',
  },
  bottomBarContainer: {
    position: 'absolute',
    bottom: hp(20),
    left: wp(16),
    right: wp(16),
    height: hp(65),
    backgroundColor: '#333333',
    borderRadius: hp(35),
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: wp(12),
    elevation: 10,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 5 },
    shadowOpacity: 0.4,
    shadowRadius: 6,
  },
  bottomBarIconContainer: {
    flex: 1,
    height: '100%',
    justifyContent: 'center',
    alignItems: 'center',
  },
  bottomBarDivider: {
    width: 1,
    height: hp(20),
    backgroundColor: '#444',
  },
  expandedMenuContainer: {
    position: 'absolute',
    bottom: hp(95),
    left: 0,
    right: 0,
    alignItems: 'center',
    zIndex: 100,
  },
  fullScreenOverlay: {
    position: 'absolute',
    top: 0,
    bottom: 0,
    left: 0,
    right: 0,
    zIndex: 90,
  },
  expandedMenuOverlay: {
    backgroundColor: '#333333',
    borderRadius: hp(25),
    flexDirection: 'row',
    padding: hp(18),
    paddingHorizontal: wp(25),
    justifyContent: 'space-between',
    alignItems: 'center',
    width: '92%',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.5,
    shadowRadius: 15,
    elevation: 12,
  },
  gridMenuOverlay: {
    backgroundColor: '#333333',
    borderRadius: hp(25),
    padding: hp(20),
    paddingVertical: hp(25),
    width: '92%',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.5,
    shadowRadius: 15,
    elevation: 12,
  },
  gridRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: hp(18),
  },
  gridMenuItem: {
    alignItems: 'center',
    width: '25%',
  },
  menuItem: {
    alignItems: 'center',
  },
  menuIconWrapper: {
    marginBottom: hp(8),
  },
  menuItemText: {
    color: '#e48616',
    fontSize: hp(12),
    marginTop: hp(5),
    textAlign: 'center',
    fontFamily: 'Outfit-Medium',
  },
});

export default styles;
