import { StyleSheet, Platform } from 'react-native';
import { hp, wp } from '../../utils/responsive';
import { COLORS } from '../../constants';

const styles = StyleSheet.create({
  container: {
    flex: 1,
  },
  mainContainer: {
    backgroundColor: '#FEF9F5',
    flex: 1,
    paddingHorizontal: 15,
    paddingTop: 15,
    borderTopLeftRadius: 30,
    borderTopRightRadius: 30,
    overflow: 'hidden',
  },
  headerText: {
    fontSize: 20,
    fontWeight: '700',
    color: COLORS.white,
    textAlign: 'center',
    fontFamily: 'Outfit-Bold',
    width: '100%',
    paddingHorizontal: 60,
  },
  sectionHeaderContainer: {
    justifyContent: 'space-between',
    flexDirection: 'row',
    marginBottom: 15,
  },
  sectionHeader: {
    fontSize: hp(16),
    fontWeight: '700',
    lineHeight: hp(22),
    color: COLORS.black,
    fontFamily: 'Outfit-Bold',
  },
  recentViewContainer: {
    backgroundColor: COLORS.white,
    borderRadius: 15,
    padding: 12,
    marginRight: 15,
    width: wp(280),
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.1,
    shadowRadius: 8,
    elevation: 4,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.3)',
  },
  cardImage: {
    height: hp(120),
    width: '100%',
    borderRadius: 15,
  },
  recentCardText: {
    fontSize: hp(14),
    lineHeight: 20,
    fontWeight: '400',
    color: COLORS.firefly,
    fontFamily: 'Outfit-Regular',
  },
  recentTextContainer: {
    width: '100%',
    marginTop: 10,
  },
  recentCardTimeText: {
    fontSize: hp(12),
    lineHeight: hp(16),
    fontWeight: '400',
    color: COLORS.gray,
    marginTop: hp(5),
    fontFamily: 'Outfit-Regular',
  },
  progressBackground: {
    height: 8,
    backgroundColor: '#f0f0f0',
    borderRadius: 4,
    overflow: 'hidden',
    marginTop: 10,
  },
  progressBar: {
    height: '100%',
    backgroundColor: COLORS.orange,
    borderRadius: 4,
  },
  separator: {
    height: 20,
  },
  flatSeparator: {
    width: 15,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 20,
    paddingTop: 10,
    paddingBottom: 20,
  },
  sectionViewAll: {
    fontSize: hp(14),
    fontWeight: '600',
    color: COLORS.orange,
    fontFamily: 'Outfit-SemiBold',
  },
  AudioContainer: {
    flex: 1,
    backgroundColor: COLORS.white,
    borderRadius: 20,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.1,
    shadowRadius: 10,
    elevation: 4,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.3)',
    overflow: 'hidden',
    marginBottom: 5,
  },
  audioCardImage: {
    height: hp(180),
    width: '100%',
  },
  audioTextContainer: {
    padding: 15,
  },
  audioCardTitle: {
    fontSize: hp(16),
    lineHeight: hp(22),
    fontWeight: '700',
    color: COLORS.firefly,
    fontFamily: 'Outfit-Bold',
  },
  audioCardDescription: {
    fontSize: hp(14),
    lineHeight: hp(20),
    fontWeight: '400',
    color: '#666',
    marginTop: 5,
    fontFamily: 'Outfit-Regular',
  },
  iconContainer: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: 'rgba(251, 115, 43, 0.1)',
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 10,
  },
  headerIconContainer: {
    width: 40,
    height: 40,
    justifyContent: 'center',
    alignItems: 'center',
    position: 'absolute',
    left: hp(16),
    zIndex: 10,
  },
  imageContainer: {
    marginTop: 10,
    flexDirection: 'row',
  },
  oneXText: {
    fontSize: hp(14),
    fontWeight: '700',
    color: COLORS.firefly,
    fontFamily: 'Outfit-Bold',
  },
  cardSeparator: {
    height: 1,
    backgroundColor: '#f0f0f0',
    marginVertical: 15,
  },
  audioCardText: {
    fontSize: hp(15),
    lineHeight: hp(22),
    fontWeight: '400',
    color: COLORS.firefly,
    textAlign: 'center',
    fontFamily: 'Outfit-Medium',
  },
});

export default styles;
