import { StyleSheet, Platform } from 'react-native';
import { hp, wp } from '../../utils/responsive';
import { COLORS } from '../../constants';

const styles = StyleSheet.create({
  container: {
    flex: 1,
  },
  mainContainer: {
    backgroundColor: '#FEF9F5',
    flex: 1,
    paddingHorizontal: 20,
    paddingTop: 15,
    borderTopLeftRadius: 30,
    borderTopRightRadius: 30,
    overflow: 'hidden',
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 20,
    paddingTop: 10,
    paddingBottom: 20,
  },
  chakraStyle: {
    position: 'absolute',
    right: hp(-200),
    top: hp(-200),
    height: hp(450),
    width: hp(470),
    opacity: 0.4,
  },
  heading: {
    fontSize: 20,
    color: COLORS.white,
    fontWeight: '700',
    textAlign: 'center',
    fontFamily: 'Outfit-Bold',
    flex: 1,
    paddingHorizontal: 50,
  },
  iconContainer: {
    width: 40,
    height: 40,
    justifyContent: 'center',
    alignItems: 'center',
    position: 'absolute',
    left: hp(16),
    zIndex: 10,
  },
  icon: {
    height: hp(24),
    width: hp(24),
  },
  contentContainerStyle: {
    paddingBottom: hp(24),
  },
  cardContainer: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: COLORS.white,
    borderRadius: 15,
    padding: 15,
    marginBottom: 15,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.1,
    shadowRadius: 8,
    elevation: 4,
    borderWidth: 1,
    borderColor: 'rgba(0,0,0,0.05)',
  },
  boarderCardContainer: {
    flex: 1,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    backgroundColor: COLORS.white,
    borderRadius: 20,
    padding: 15,
    borderWidth: 2,
    borderColor: COLORS.orange,
    shadowColor: COLORS.orange,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.2,
    shadowRadius: 8,
    elevation: 6,
  },
  cardImage: {
    height: hp(70),
    width: hp(70),
    borderRadius: 10,
  },
  cardIconContainer: {
    height: hp(80),
    width: hp(80),
    borderRadius: 15,
    backgroundColor: 'rgba(251, 115, 43, 0.1)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  cardText: {
    fontSize: hp(18),
    color: COLORS.firefly,
    fontWeight: '700',
    flex: 1,
    marginLeft: 20,
    fontFamily: 'Outfit-Bold',
  },
  cardIcon: {
    height: hp(60),
    width: hp(60),
  },
  flatListContainer: {
    flex: 1,
    marginTop: hp(10),
  },
  itemSeparator: {
    height: 15,
  },
  buttonLabel: {
    fontSize: hp(16),
    fontWeight: '700',
    color: COLORS.white,
    fontFamily: 'Outfit-Bold',
  },
  disableButtonLabel: {
    fontSize: hp(16),
    fontWeight: '700',
    color: 'rgba(255, 255, 255, 0.5)',
    fontFamily: 'Outfit-Bold',
  },
  buttonContainer: {
    backgroundColor: COLORS.orange,
    borderRadius: 15,
    marginTop: hp(20),
    height: 55,
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: COLORS.orange,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 5,
  },
  disabledButtonContainer: {
    backgroundColor: '#cccccc',
    borderRadius: 15,
    marginTop: hp(20),
    height: 55,
    justifyContent: 'center',
    alignItems: 'center',
  },
});

export default styles;
