import { StyleSheet, Platform } from 'react-native';
import { hp, wp } from '../../utils/responsive';
import { COLORS } from '../../constants';

const styles = StyleSheet.create({
  container: {
    flex: 1,
  },
  chakraStyle: {
    position: 'absolute',
    right: hp(-200),
    top: hp(-200),
    height: hp(450),
    width: hp(470),
    opacity: 0.4,
  },
  chapterImage: {
    height: hp(40),
    width: hp(40),
    borderRadius: 20,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.3)',
  },
  mainContainer: {
    backgroundColor: '#FEF9F5',
    flex: 1,
    paddingHorizontal: 20,
    paddingTop: 15,
    borderTopLeftRadius: 30,
    borderTopRightRadius: 30,
    overflow: 'hidden',
  },
  header: { marginHorizontal: wp(16) },
  headerText: {
    fontSize: 20,
    fontWeight: '700',
    color: COLORS.white,
    textAlign: 'center',
    fontFamily: 'Outfit-Bold',
    width: '100%',
    paddingHorizontal: 80,
  },
  headerComponent: {
    flexDirection: 'row',
    marginTop: hp(30),
    alignItems: 'center',
    marginHorizontal: wp(16),
  },
  headerComponentText: {
    fontSize: hp(22),
    fontWeight: '700',
    lineHeight: hp(32),
    color: COLORS.black,
    marginLeft: wp(12),
    fontFamily: 'Outfit-Bold',
  },
  headerComponentDescription: {
    fontSize: hp(14),
    fontWeight: '400',
    lineHeight: hp(22),
    color: '#666',
    marginBottom: 20,
    marginHorizontal: 20,
    fontFamily: 'Outfit-Regular',
    textAlign: 'justify',
  },
  flatListContainer: {
    flex: 1,
  },
  handle: {
    marginTop: hp(10),
    width: wp(70),
    height: hp(5),
    borderRadius: hp(10),
    backgroundColor: COLORS.alto,
    alignSelf: 'center',
  },
  shlokItem: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(255, 255, 255, 0.9)',
    padding: 15,
    borderRadius: 15,
    marginBottom: 12,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.1,
    shadowRadius: 8,
    elevation: 4,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.3)',
  },
  listItem: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(255, 255, 255, 0.9)',
    borderRadius: 15,
    padding: 15,
    marginBottom: 12,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.08,
    shadowRadius: 8,
    elevation: 3,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.3)',
  },
  cardContainer: {
    backgroundColor: '#FEF9F5',
    borderRadius: 20,
    flexDirection: 'row',
    padding: 15,
    marginHorizontal: 5,
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.1,
    shadowRadius: 10,
    elevation: 4,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.3)',
  },
  cardImage: {
    height: hp(80),
    width: wp(75),
    borderRadius: hp(6),
  },
  contentContainerStyle: {
    flexGrow: 1,
    marginTop: hp(10),
    paddingBottom: hp(24),
  },
  itemSeparator: {
    height: hp(20),
  },
  cardTitle: {
    fontSize: hp(18),
    fontWeight: '700',
    lineHeight: hp(26),
    color: COLORS.black,
    fontFamily: 'Outfit-Bold',
  },
  cardTitle1: {
    fontSize: hp(16),
    fontWeight: '600',
    lineHeight: hp(22),
    color: COLORS.orange,
    fontFamily: 'Outfit-SemiBold',
  },
  languageText: {
    fontSize: hp(14),
    fontWeight: '400',
    color: COLORS.gray,
    fontFamily: 'Outfit-Regular',
  },
  textContainer: {
    marginLeft: wp(15),
    marginVertical: wp(5),
    marginRight: wp(5),
    flex: 1,
    flexShrink: 1,
  },
  timeText: {
    fontSize: hp(15),
    fontWeight: '400',
    lineHeight: hp(22),
    color: COLORS.doveGray,
  },
  headerSubContainer: {
    height: hp(30),
    width: hp(30),
    justifyContent: 'center',
    alignItems: 'center',
  },
  icon: {
    height: hp(24),
    width: hp(24),
  },
  headerContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 20,
    paddingTop: 10,
    paddingBottom: 20,
  },
  headerIconContainer: {
    width: 40,
    height: 40,
    justifyContent: 'center',
    alignItems: 'center',
    position: 'absolute',
    left: hp(16),
    zIndex: 10,
  },
  headerSearchContainer: {
    height: hp(30),
    width: hp(30),
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: wp(16),
  },
  imageContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    position: 'absolute',
    left: hp(16),
    zIndex: 10,
  },
  headerIcons: {
    flexDirection: 'row',
    alignItems: 'center',
    position: 'absolute',
    right: hp(16),
    zIndex: 10,
  },
});

export default styles;
